// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"wot-statistics-server/api/controller"
	"wot-statistics-server/config"
	"wot-statistics-server/repository"
	"wot-statistics-server/usecase"
)

// Injectors from tank_module.go:

func InitializeTankController(appConfig *config.AppConfig) *controller.TankController {
	tankRepository := repository.NewTankRepository(appConfig)
	tankUseCase := usecase.NewTankUseCase(tankRepository)
	tankController := controller.NewTankController(tankUseCase)
	return tankController
}

// tank_module.go:

var TankSet = wire.NewSet(repository.NewTankRepository, usecase.NewTankUseCase, controller.NewTankController)
